### PR TITLE
added logo for the upcoming IBM PowerVC provider

### PR DESCRIPTION
**Pull request by iv1111**

### CODE REVIEW

**Comment by iv1111** [comment]
Currently the only logo we could find.

**Comment by iv1111** [comment]
Mentioning just for the context. This will soon be moved into MIQ:
https://github.com/iv1111/manageiq-providers-ibm_power_vc

**Comment by Fryguy** [comment]
I can merge for now, but we're definitely going to need a different logo.  This logo is very wide, and needs to be more of a square.  In its current form it will be ultra-compressed in a quadicon, and effectively unreadable.

**Comment by Fryguy** [comment]
cc @jaywcarman

**Comment by jaywcarman** [comment]
> we're definitely going to need a different logo.

@iv1111 I found some possibilities used for official PowerVC public accounts:
PowerVC LinkedIn https://www.linkedin.com/groups/6610502/
PowerVC YouTube https://www.youtube.com/channel/UCj7dmNML07cV8Mw9sw7fcpw
Recent videos posted on the youtube channel use an icon proportioned logo (screenshot below). I'll reach out internally and see if we can find the origin, and :crossed_fingers: _get a vector image_ :crossed_fingers:.
image

**Comment by iv1111** [comment]
> @iv1111 I found some possibilities used for official PowerVC public accounts:

This would definitely look better but the question is whether we can use it as it's an outdated logo for PVC.

**Comment by Fryguy** [comment]
Backported to `morphy` in commit 41975f1571e8caa42c5ddf08da314289c9753c16.

```text
commit 41975f1571e8caa42c5ddf08da314289c9753c16
Author: Jason Frey <fryguy9@gmail.com>
Date:   Wed Apr 28 09:56:13 2021 -0400

    Merge pull request #49 from iv1111/powervc
    
    added logo for the upcoming IBM PowerVC provider
    
    (cherry picked from commit 32fbae6b5eb35dbfaab0b502f36b7582138ad44b)
```

**Pull request merged**
