### PR TITLE
Automate methods

### PR DESCRIPTION
**Pull request by martinpovolny**
Part of: https://github.com/ManageIQ/manageiq-ui-classic/pull/5295

I have actually tested only one of the 2. ~~Looking how to get test data.~~ (@lfu tested it)

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot add_reviewer @epwinchell

**Comment by martinpovolny** [comment]
replaced with  'ff ff-load-balancer' according to @lfu 's testing : https://github.com/ManageIQ/manageiq-ui-classic/pull/5295

**Comment by martinpovolny** [comment]
ping @skateman

**Comment by skateman** [comment]
@martinpovolny can you provide us some screenshots so we can see this with @epwinchell?

**Comment by martinpovolny** [comment]
No. I cannot (as I wrote above).

@lfu, can  you, please, make a pretty picture for @skateman ?

**Comment by martinpovolny** [comment]
picture with one of the icons is here:

https://user-images.githubusercontent.com/2593270/56383489-e4793880-61e7-11e9-8637-4c48a81e991e.png

(from https://github.com/ManageIQ/manageiq-ui-classic/pull/5295)

**Comment by lfu** [comment]
Screen Shot 2019-04-22 at 10 05 33

**Comment by epwinchell** [comment]
test_template_method doesn't seem to be using ff-method:

Screen Shot 2019-04-22 at 10 09 55 AM

**Comment by lfu** [comment]
```test_template_method``` is an instance. ```test_workflow_template``` is a workflow template method.

**Pull request merged**
