### PR TITLE
Update Azure logo

### PR DESCRIPTION
**Pull request by epwinchell**
This PR replaces the Microsoft Azure logo to the current version

Old
screen shot 2019-01-15 at 1 05 10 pm

New
screen shot 2019-01-15 at 12 32 34 pm

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot assign @skateman

**Comment by Fryguy** [comment]
I haven't finished updating this repo yet, so for now I'll assign manually (also the bot might not yet respond as well as tests failing).

**Comment by skateman** [comment]
@Fryguy I assume I can ignore the CI failure...

**Comment by Fryguy** [comment]
Yeah, ignore it for now.

**Pull request merged**
