### PR TITLE
Azure Stack logo

### PR DESCRIPTION
**Pull request by miha-plesko**
Tadaaa intrducing SVG logo for incomming AzureStack cloud + network provider 📯

### CODE REVIEW

**Comment by himdel** [comment]
:+1: cc @skateman, @epwinchell I don't know the process here :)

**Comment by epwinchell** [comment]
@miha-plesko Please add symlinks of vendor-azure.svg rather than copying the file. Thanks.

**Comment by miha-plesko** [comment]
@epwinchell makes sense 👍

**Comment by epwinchell** [comment]
Both should be symlinks to the existing  vendor-azure.svg

**Pull request merged**
